version: "3.4"
services:
  maxsum-dev:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: maxsum-dev
    volumes:
      - ./src:/src
    ports:
      - "4000:4000"
